version = 0.1
[default.deploy.parameters]
stack_name = "ptv-departure-lambda"
resolve_s3 = true
s3_prefix = "ptv-departure-lambda"
region = "ap-southeast-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
